# Generated by Django 4.1.7 on 2023-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='employment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
